/* File automatically generated by asdl_js.py. */

/* Object that holds all nodes */
SkAst.astnodes = {};

/* ----- expr_context ----- */
/** @constructor */
SkAst.astnodes.Load = function Load() {}
/** @constructor */
SkAst.astnodes.Store = function Store() {}
/** @constructor */
SkAst.astnodes.Del = function Del() {}
/** @constructor */
SkAst.astnodes.AugLoad = function AugLoad() {}
/** @constructor */
SkAst.astnodes.AugStore = function AugStore() {}
/** @constructor */
SkAst.astnodes.Param = function Param() {}

/* ----- boolop ----- */
/** @constructor */
SkAst.astnodes.And = function And() {}
/** @constructor */
SkAst.astnodes.Or = function Or() {}

/* ----- operator ----- */
/** @constructor */
SkAst.astnodes.Add = function Add() {}
/** @constructor */
SkAst.astnodes.Sub = function Sub() {}
/** @constructor */
SkAst.astnodes.Mult = function Mult() {}
/** @constructor */
SkAst.astnodes.MatMult = function MatMult() {}
/** @constructor */
SkAst.astnodes.Div = function Div() {}
/** @constructor */
SkAst.astnodes.Mod = function Mod() {}
/** @constructor */
SkAst.astnodes.Pow = function Pow() {}
/** @constructor */
SkAst.astnodes.LShift = function LShift() {}
/** @constructor */
SkAst.astnodes.RShift = function RShift() {}
/** @constructor */
SkAst.astnodes.BitOr = function BitOr() {}
/** @constructor */
SkAst.astnodes.BitXor = function BitXor() {}
/** @constructor */
SkAst.astnodes.BitAnd = function BitAnd() {}
/** @constructor */
SkAst.astnodes.FloorDiv = function FloorDiv() {}

/* ----- unaryop ----- */
/** @constructor */
SkAst.astnodes.Invert = function Invert() {}
/** @constructor */
SkAst.astnodes.Not = function Not() {}
/** @constructor */
SkAst.astnodes.UAdd = function UAdd() {}
/** @constructor */
SkAst.astnodes.USub = function USub() {}

/* ----- cmpop ----- */
/** @constructor */
SkAst.astnodes.Eq = function Eq() {}
/** @constructor */
SkAst.astnodes.NotEq = function NotEq() {}
/** @constructor */
SkAst.astnodes.Lt = function Lt() {}
/** @constructor */
SkAst.astnodes.LtE = function LtE() {}
/** @constructor */
SkAst.astnodes.Gt = function Gt() {}
/** @constructor */
SkAst.astnodes.GtE = function GtE() {}
/** @constructor */
SkAst.astnodes.Is = function Is() {}
/** @constructor */
SkAst.astnodes.IsNot = function IsNot() {}
/** @constructor */
SkAst.astnodes.In = function In() {}
/** @constructor */
SkAst.astnodes.NotIn = function NotIn() {}







/* ---------------------- */
/* constructors for nodes */
/* ---------------------- */





/** @constructor */
SkAst.astnodes.Module = function Module(/* {asdl_seq *} */ body, /* {string} */
                                          docstring)
{
    this.body = body;
    this.docstring = docstring;
    return this;
}

/** @constructor */
SkAst.astnodes.Interactive = function Interactive(/* {asdl_seq *} */ body)
{
    this.body = body;
    return this;
}

/** @constructor */
SkAst.astnodes.Expression = function Expression(/* {expr_ty} */ body)
{
    this.body = body;
    return this;
}

/** @constructor */
SkAst.astnodes.Suite = function Suite(/* {asdl_seq *} */ body)
{
    this.body = body;
    return this;
}

/** @constructor */
SkAst.astnodes.FunctionDef = function FunctionDef(/* {identifier} */ name, /*
                                                    {arguments__ty} */ args, /*
                                                    {asdl_seq *} */ body, /*
                                                    {asdl_seq *} */
                                                    decorator_list, /*
                                                    {expr_ty} */ returns, /*
                                                    {string} */ docstring, /*
                                                    {int} */ lineno, /* {int}
                                                    */ col_offset, /* {int} */
                                                    end_lineno, /* {int} */
                                                    end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.name = name;
    this.args = args;
    this.body = body;
    this.decorator_list = decorator_list;
    this.returns = returns;
    this.docstring = docstring;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.AsyncFunctionDef = function AsyncFunctionDef(/* {identifier} */
                                                              name, /*
                                                              {arguments__ty}
                                                              */ args, /*
                                                              {asdl_seq *} */
                                                              body, /*
                                                              {asdl_seq *} */
                                                              decorator_list,
                                                            /* {expr_ty} */
                                                              returns, /*
                                                              {string} */
                                                              docstring, /*
                                                              {int} */ lineno,
                                                            /* {int} */
                                                              col_offset, /*
                                                              {int} */
                                                              end_lineno, /*
                                                              {int} */
                                                              end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.name = name;
    this.args = args;
    this.body = body;
    this.decorator_list = decorator_list;
    this.returns = returns;
    this.docstring = docstring;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.ClassDef = function ClassDef(/* {identifier} */ name, /* {asdl_seq
                                              *} */ bases, /* {asdl_seq *} */
                                              keywords, /* {asdl_seq *} */
                                              body, /* {asdl_seq *} */
                                              decorator_list, /* {string} */
                                              docstring, /* {int} */ lineno, /*
                                              {int} */ col_offset, /* {int} */
                                              end_lineno, /* {int} */
                                              end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.name = name;
    this.bases = bases;
    this.keywords = keywords;
    this.body = body;
    this.decorator_list = decorator_list;
    this.docstring = docstring;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Return = function Return(/* {expr_ty} */ value, /* {int} */ lineno,
                                        /* {int} */ col_offset, /* {int} */
                                          end_lineno, /* {int} */
                                          end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.value = value;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Delete = function Delete(/* {asdl_seq *} */ targets, /* {int} */
                                          lineno, /* {int} */ col_offset, /*
                                          {int} */ end_lineno, /* {int} */
                                          end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.targets = targets;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Assign = function Assign(/* {asdl_seq *} */ targets, /* {expr_ty}
                                          */ value, /* {int} */ lineno, /*
                                          {int} */ col_offset, /* {int} */
                                          end_lineno, /* {int} */
                                          end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.targets = targets;
    this.value = value;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.AugAssign = function AugAssign(/* {expr_ty} */ target, /*
                                                {operator_ty} */ op, /*
                                                {expr_ty} */ value, /* {int} */
                                                lineno, /* {int} */ col_offset,
                                              /* {int} */ end_lineno, /*
                                                {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.target = target;
    this.op = op;
    this.value = value;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.AnnAssign = function AnnAssign(/* {expr_ty} */ target, /* {expr_ty}
                                                */ annotation, /* {expr_ty} */
                                                value, /* {int} */ simple, /*
                                                {int} */ lineno, /* {int} */
                                                col_offset, /* {int} */
                                                end_lineno, /* {int} */
                                                end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.target = target;
    this.annotation = annotation;
    this.value = value;
    this.simple = simple;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.For = function For(/* {expr_ty} */ target, /* {expr_ty} */ iter, /*
                                    {asdl_seq *} */ body, /* {asdl_seq *} */
                                    orelse, /* {int} */ lineno, /* {int} */
                                    col_offset, /* {int} */ end_lineno, /*
                                    {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.target = target;
    this.iter = iter;
    this.body = body;
    this.orelse = orelse;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.AsyncFor = function AsyncFor(/* {expr_ty} */ target, /* {expr_ty}
                                              */ iter, /* {asdl_seq *} */ body,
                                            /* {asdl_seq *} */ orelse, /*
                                              {int} */ lineno, /* {int} */
                                              col_offset, /* {int} */
                                              end_lineno, /* {int} */
                                              end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.target = target;
    this.iter = iter;
    this.body = body;
    this.orelse = orelse;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.While = function While(/* {expr_ty} */ test, /* {asdl_seq *} */
                                        body, /* {asdl_seq *} */ orelse, /*
                                        {int} */ lineno, /* {int} */
                                        col_offset, /* {int} */ end_lineno, /*
                                        {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.test = test;
    this.body = body;
    this.orelse = orelse;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.If = function If(/* {expr_ty} */ test, /* {asdl_seq *} */ body, /*
                                  {asdl_seq *} */ orelse, /* {int} */ lineno,
                                /* {int} */ col_offset, /* {int} */
                                  end_lineno, /* {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.test = test;
    this.body = body;
    this.orelse = orelse;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.With = function With(/* {asdl_seq *} */ items, /* {asdl_seq *} */
                                      body, /* {int} */ lineno, /* {int} */
                                      col_offset, /* {int} */ end_lineno, /*
                                      {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.items = items;
    this.body = body;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.AsyncWith = function AsyncWith(/* {asdl_seq *} */ items, /*
                                                {asdl_seq *} */ body, /* {int}
                                                */ lineno, /* {int} */
                                                col_offset, /* {int} */
                                                end_lineno, /* {int} */
                                                end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.items = items;
    this.body = body;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Raise = function Raise(/* {expr_ty} */ exc, /* {expr_ty} */ cause,
                                      /* {expr_ty} */ inst, /* {expr_ty} */
                                        tback, /* {int} */ lineno, /* {int} */
                                        col_offset, /* {int} */ end_lineno, /*
                                        {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.exc = exc;
    this.cause = cause;
    this.inst = inst;
    this.tback = tback;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Try = function Try(/* {asdl_seq *} */ body, /* {asdl_seq *} */
                                    handlers, /* {asdl_seq *} */ orelse, /*
                                    {asdl_seq *} */ finalbody, /* {int} */
                                    lineno, /* {int} */ col_offset, /* {int} */
                                    end_lineno, /* {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.body = body;
    this.handlers = handlers;
    this.orelse = orelse;
    this.finalbody = finalbody;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Assert = function Assert(/* {expr_ty} */ test, /* {expr_ty} */ msg,
                                        /* {int} */ lineno, /* {int} */
                                          col_offset, /* {int} */ end_lineno,
                                        /* {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.test = test;
    this.msg = msg;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Import = function Import(/* {asdl_seq *} */ names, /* {int} */
                                          lineno, /* {int} */ col_offset, /*
                                          {int} */ end_lineno, /* {int} */
                                          end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.names = names;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.ImportFrom = function ImportFrom(/* {identifier} */ module, /*
                                                  {asdl_seq *} */ names, /*
                                                  {int} */ level, /* {int} */
                                                  lineno, /* {int} */
                                                  col_offset, /* {int} */
                                                  end_lineno, /* {int} */
                                                  end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.module = module;
    this.names = names;
    this.level = level;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Global = function Global(/* {asdl_seq *} */ names, /* {int} */
                                          lineno, /* {int} */ col_offset, /*
                                          {int} */ end_lineno, /* {int} */
                                          end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.names = names;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Nonlocal = function Nonlocal(/* {asdl_seq *} */ names, /* {int} */
                                              lineno, /* {int} */ col_offset,
                                            /* {int} */ end_lineno, /* {int}
                                              */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.names = names;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Expr = function Expr(/* {expr_ty} */ value, /* {int} */ lineno, /*
                                      {int} */ col_offset, /* {int} */
                                      end_lineno, /* {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.value = value;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Pass = function Pass(/* {int} */ lineno, /* {int} */ col_offset, /*
                                      {int} */ end_lineno, /* {int} */
                                      end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Break = function Break(/* {int} */ lineno, /* {int} */ col_offset,
                                      /* {int} */ end_lineno, /* {int} */
                                        end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Continue = function Continue(/* {int} */ lineno, /* {int} */
                                              col_offset, /* {int} */
                                              end_lineno, /* {int} */
                                              end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Print = function Print(/* {expr_ty} */ dest, /* {asdl_seq *} */
                                        values, /* {int} */ nl, /* {int} */
                                        lineno, /* {int} */ col_offset, /*
                                        {int} */ end_lineno, /* {int} */
                                        end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.dest = dest;
    this.values = values;
    this.nl = nl;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Debugger = function Debugger(/* {int} */ lineno, /* {int} */
                                              col_offset, /* {int} */
                                              end_lineno, /* {int} */
                                              end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.BoolOp = function BoolOp(/* {boolop_ty} */ op, /* {asdl_seq *} */
                                          values, /* {int} */ lineno, /* {int}
                                          */ col_offset, /* {int} */
                                          end_lineno, /* {int} */
                                          end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.op = op;
    this.values = values;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.BinOp = function BinOp(/* {expr_ty} */ left, /* {operator_ty} */
                                        op, /* {expr_ty} */ right, /* {int} */
                                        lineno, /* {int} */ col_offset, /*
                                        {int} */ end_lineno, /* {int} */
                                        end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.left = left;
    this.op = op;
    this.right = right;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.UnaryOp = function UnaryOp(/* {unaryop_ty} */ op, /* {expr_ty} */
                                            operand, /* {int} */ lineno, /*
                                            {int} */ col_offset, /* {int} */
                                            end_lineno, /* {int} */
                                            end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.op = op;
    this.operand = operand;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Lambda = function Lambda(/* {arguments__ty} */ args, /* {expr_ty}
                                          */ body, /* {int} */ lineno, /* {int}
                                          */ col_offset, /* {int} */
                                          end_lineno, /* {int} */
                                          end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.args = args;
    this.body = body;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.IfExp = function IfExp(/* {expr_ty} */ test, /* {expr_ty} */ body,
                                      /* {expr_ty} */ orelse, /* {int} */
                                        lineno, /* {int} */ col_offset, /*
                                        {int} */ end_lineno, /* {int} */
                                        end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.test = test;
    this.body = body;
    this.orelse = orelse;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Dict = function Dict(/* {asdl_seq *} */ keys, /* {asdl_seq *} */
                                      values, /* {int} */ lineno, /* {int} */
                                      col_offset, /* {int} */ end_lineno, /*
                                      {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.keys = keys;
    this.values = values;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Set = function Set(/* {asdl_seq *} */ elts, /* {int} */ lineno, /*
                                    {int} */ col_offset, /* {int} */
                                    end_lineno, /* {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.elts = elts;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.ListComp = function ListComp(/* {expr_ty} */ elt, /* {asdl_seq *}
                                              */ generators, /* {int} */
                                              lineno, /* {int} */ col_offset,
                                            /* {int} */ end_lineno, /* {int}
                                              */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.elt = elt;
    this.generators = generators;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.SetComp = function SetComp(/* {expr_ty} */ elt, /* {asdl_seq *} */
                                            generators, /* {int} */ lineno, /*
                                            {int} */ col_offset, /* {int} */
                                            end_lineno, /* {int} */
                                            end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.elt = elt;
    this.generators = generators;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.DictComp = function DictComp(/* {expr_ty} */ key, /* {expr_ty} */
                                              value, /* {asdl_seq *} */
                                              generators, /* {int} */ lineno,
                                            /* {int} */ col_offset, /* {int}
                                              */ end_lineno, /* {int} */
                                              end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.key = key;
    this.value = value;
    this.generators = generators;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.GeneratorExp = function GeneratorExp(/* {expr_ty} */ elt, /*
                                                      {asdl_seq *} */
                                                      generators, /* {int} */
                                                      lineno, /* {int} */
                                                      col_offset, /* {int} */
                                                      end_lineno, /* {int} */
                                                      end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.elt = elt;
    this.generators = generators;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Await = function Await(/* {expr_ty} */ value, /* {int} */ lineno,
                                      /* {int} */ col_offset, /* {int} */
                                        end_lineno, /* {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.value = value;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Yield = function Yield(/* {expr_ty} */ value, /* {int} */ lineno,
                                      /* {int} */ col_offset, /* {int} */
                                        end_lineno, /* {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.value = value;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.YieldFrom = function YieldFrom(/* {expr_ty} */ value, /* {int} */
                                                lineno, /* {int} */ col_offset,
                                              /* {int} */ end_lineno, /*
                                                {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.value = value;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Compare = function Compare(/* {expr_ty} */ left, /* {asdl_int_seq
                                            *} */ ops, /* {asdl_seq *} */
                                            comparators, /* {int} */ lineno, /*
                                            {int} */ col_offset, /* {int} */
                                            end_lineno, /* {int} */
                                            end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.left = left;
    this.ops = ops;
    this.comparators = comparators;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Call = function Call(/* {expr_ty} */ func, /* {asdl_seq *} */ args,
                                    /* {asdl_seq *} */ keywords, /* {int} */
                                      lineno, /* {int} */ col_offset, /* {int}
                                      */ end_lineno, /* {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.func = func;
    this.args = args;
    this.keywords = keywords;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Num = function Num(/* {object} */ n, /* {int} */ lineno, /* {int}
                                    */ col_offset, /* {int} */ end_lineno, /*
                                    {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.n = n;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Str = function Str(/* {string} */ s, /* {int} */ lineno, /* {int}
                                    */ col_offset, /* {int} */ end_lineno, /*
                                    {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.s = s;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.FormattedValue = function FormattedValue(/* {expr_ty} */ value, /*
                                                          {int} */ conversion,
                                                        /* {expr_ty} */
                                                          format_spec, /* {int}
                                                          */ lineno, /* {int}
                                                          */ col_offset, /*
                                                          {int} */ end_lineno,
                                                        /* {int} */
                                                          end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.value = value;
    this.conversion = conversion;
    this.format_spec = format_spec;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.JoinedStr = function JoinedStr(/* {asdl_seq *} */ values, /* {int}
                                                */ lineno, /* {int} */
                                                col_offset, /* {int} */
                                                end_lineno, /* {int} */
                                                end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.values = values;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Bytes = function Bytes(/* {bytes} */ s, /* {int} */ lineno, /*
                                        {int} */ col_offset, /* {int} */
                                        end_lineno, /* {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.s = s;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.NameConstant = function NameConstant(/* {singleton} */ value, /*
                                                      {int} */ lineno, /* {int}
                                                      */ col_offset, /* {int}
                                                      */ end_lineno, /* {int}
                                                      */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.value = value;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Ellipsis = function Ellipsis(/* {int} */ lineno, /* {int} */
                                              col_offset, /* {int} */
                                              end_lineno, /* {int} */
                                              end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Constant = function Constant(/* {constant} */ value, /* {int} */
                                              lineno, /* {int} */ col_offset,
                                            /* {int} */ end_lineno, /* {int}
                                              */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.value = value;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Attribute = function Attribute(/* {expr_ty} */ value, /*
                                                {identifier} */ attr, /*
                                                {expr_context_ty} */ ctx, /*
                                                {int} */ lineno, /* {int} */
                                                col_offset, /* {int} */
                                                end_lineno, /* {int} */
                                                end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.value = value;
    this.attr = attr;
    this.ctx = ctx;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Subscript = function Subscript(/* {expr_ty} */ value, /* {slice_ty}
                                                */ slice, /* {expr_context_ty}
                                                */ ctx, /* {int} */ lineno, /*
                                                {int} */ col_offset, /* {int}
                                                */ end_lineno, /* {int} */
                                                end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.value = value;
    this.slice = slice;
    this.ctx = ctx;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Starred = function Starred(/* {expr_ty} */ value, /*
                                            {expr_context_ty} */ ctx, /* {int}
                                            */ lineno, /* {int} */ col_offset,
                                          /* {int} */ end_lineno, /* {int} */
                                            end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.value = value;
    this.ctx = ctx;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Name = function Name(/* {identifier} */ id, /* {expr_context_ty} */
                                      ctx, /* {int} */ lineno, /* {int} */
                                      col_offset, /* {int} */ end_lineno, /*
                                      {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.id = id;
    this.ctx = ctx;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.List = function List(/* {asdl_seq *} */ elts, /* {expr_context_ty}
                                      */ ctx, /* {int} */ lineno, /* {int} */
                                      col_offset, /* {int} */ end_lineno, /*
                                      {int} */ end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.elts = elts;
    this.ctx = ctx;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Tuple = function Tuple(/* {asdl_seq *} */ elts, /*
                                        {expr_context_ty} */ ctx, /* {int} */
                                        lineno, /* {int} */ col_offset, /*
                                        {int} */ end_lineno, /* {int} */
                                        end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.elts = elts;
    this.ctx = ctx;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.Slice = function Slice(/* {expr_ty} */ lower, /* {expr_ty} */
                                        upper, /* {expr_ty} */ step)
{
    this.lower = lower;
    this.upper = upper;
    this.step = step;
    return this;
}

/** @constructor */
SkAst.astnodes.ExtSlice = function ExtSlice(/* {asdl_seq *} */ dims)
{
    this.dims = dims;
    return this;
}

/** @constructor */
SkAst.astnodes.Index = function Index(/* {expr_ty} */ value)
{
    this.value = value;
    return this;
}

/** @constructor */
SkAst.astnodes.comprehension = function comprehension(/* {expr_ty} */ target, /*
                                                        {expr_ty} */ iter, /*
                                                        {asdl_seq *} */ ifs, /*
                                                        {int} */ is_async)
{
    this.target = target;
    this.iter = iter;
    this.ifs = ifs;
    this.is_async = is_async;
    return this;
}

/** @constructor */
SkAst.astnodes.ExceptHandler = function ExceptHandler(/* {expr_ty} */ type, /*
                                                        {identifier} */ name,
                                                      /* {asdl_seq *} */
                                                        body, /* {int} */
                                                        lineno, /* {int} */
                                                        col_offset, /* {int} */
                                                        end_lineno, /* {int} */
                                                        end_col_offset)
{
    SkAst.asserts.assert(lineno !== null && lineno !== undefined);
    SkAst.asserts.assert(col_offset !== null && col_offset !== undefined);
    SkAst.asserts.assert(end_lineno !== null && end_lineno !== undefined);
    SkAst.asserts.assert(end_col_offset !== null && end_col_offset !== undefined);
    this.type = type;
    this.name = name;
    this.body = body;
    this.lineno = lineno;
    this.col_offset = col_offset;
    this.end_lineno = end_lineno;
    this.end_col_offset = end_col_offset;
    return this;
}

/** @constructor */
SkAst.astnodes.arguments_ = function arguments_(/* {asdl_seq *} */ args, /*
                                                  {arg_ty} */ vararg, /*
                                                  {asdl_seq *} */ kwonlyargs,
                                                /* {asdl_seq *} */
                                                  kw_defaults, /* {arg_ty} */
                                                  kwarg, /* {asdl_seq *} */
                                                  defaults)
{
    this.args = args;
    this.vararg = vararg;
    this.kwonlyargs = kwonlyargs;
    this.kw_defaults = kw_defaults;
    this.kwarg = kwarg;
    this.defaults = defaults;
    return this;
}

/** @constructor */
SkAst.astnodes.arg = function arg(/* {identifier} */ arg, /* {expr_ty} */
                                    annotation)
{
    this.arg = arg;
    this.annotation = annotation;
    return this;
}

/** @constructor */
SkAst.astnodes.keyword = function keyword(/* {identifier} */ arg, /* {expr_ty} */
                                            value)
{
    this.arg = arg;
    this.value = value;
    return this;
}

/** @constructor */
SkAst.astnodes.alias = function alias(/* {identifier} */ name, /* {identifier} */
                                        asname)
{
    this.name = name;
    this.asname = asname;
    return this;
}

/** @constructor */
SkAst.astnodes.withitem = function withitem(/* {expr_ty} */ context_expr, /*
                                              {expr_ty} */ optional_vars)
{
    this.context_expr = context_expr;
    this.optional_vars = optional_vars;
    return this;
}


SkAst.astnodes.Module.prototype._astname = "Module";
SkAst.astnodes.Module.prototype._fields = [
    "body", function(n) { return n.body; },
    "docstring", function(n) { return n.docstring; }
];
SkAst.astnodes.Interactive.prototype._astname = "Interactive";
SkAst.astnodes.Interactive.prototype._fields = [
    "body", function(n) { return n.body; }
];
SkAst.astnodes.Expression.prototype._astname = "Expression";
SkAst.astnodes.Expression.prototype._fields = [
    "body", function(n) { return n.body; }
];
SkAst.astnodes.Suite.prototype._astname = "Suite";
SkAst.astnodes.Suite.prototype._fields = [
    "body", function(n) { return n.body; }
];
SkAst.astnodes.FunctionDef.prototype._astname = "FunctionDef";
SkAst.astnodes.FunctionDef.prototype._fields = [
    "name", function(n) { return n.name; },
    "args", function(n) { return n.args; },
    "body", function(n) { return n.body; },
    "decorator_list", function(n) { return n.decorator_list; },
    "returns", function(n) { return n.returns; },
    "docstring", function(n) { return n.docstring; }
];
SkAst.astnodes.AsyncFunctionDef.prototype._astname = "AsyncFunctionDef";
SkAst.astnodes.AsyncFunctionDef.prototype._fields = [
    "name", function(n) { return n.name; },
    "args", function(n) { return n.args; },
    "body", function(n) { return n.body; },
    "decorator_list", function(n) { return n.decorator_list; },
    "returns", function(n) { return n.returns; },
    "docstring", function(n) { return n.docstring; }
];
SkAst.astnodes.ClassDef.prototype._astname = "ClassDef";
SkAst.astnodes.ClassDef.prototype._fields = [
    "name", function(n) { return n.name; },
    "bases", function(n) { return n.bases; },
    "keywords", function(n) { return n.keywords; },
    "body", function(n) { return n.body; },
    "decorator_list", function(n) { return n.decorator_list; },
    "docstring", function(n) { return n.docstring; }
];
SkAst.astnodes.Return.prototype._astname = "Return";
SkAst.astnodes.Return.prototype._fields = [
    "value", function(n) { return n.value; }
];
SkAst.astnodes.Delete.prototype._astname = "Delete";
SkAst.astnodes.Delete.prototype._fields = [
    "targets", function(n) { return n.targets; }
];
SkAst.astnodes.Assign.prototype._astname = "Assign";
SkAst.astnodes.Assign.prototype._fields = [
    "targets", function(n) { return n.targets; },
    "value", function(n) { return n.value; }
];
SkAst.astnodes.AugAssign.prototype._astname = "AugAssign";
SkAst.astnodes.AugAssign.prototype._fields = [
    "target", function(n) { return n.target; },
    "op", function(n) { return n.op; },
    "value", function(n) { return n.value; }
];
SkAst.astnodes.AnnAssign.prototype._astname = "AnnAssign";
SkAst.astnodes.AnnAssign.prototype._fields = [
    "target", function(n) { return n.target; },
    "annotation", function(n) { return n.annotation; },
    "value", function(n) { return n.value; },
    "simple", function(n) { return n.simple; }
];
SkAst.astnodes.For.prototype._astname = "For";
SkAst.astnodes.For.prototype._fields = [
    "target", function(n) { return n.target; },
    "iter", function(n) { return n.iter; },
    "body", function(n) { return n.body; },
    "orelse", function(n) { return n.orelse; }
];
SkAst.astnodes.AsyncFor.prototype._astname = "AsyncFor";
SkAst.astnodes.AsyncFor.prototype._fields = [
    "target", function(n) { return n.target; },
    "iter", function(n) { return n.iter; },
    "body", function(n) { return n.body; },
    "orelse", function(n) { return n.orelse; }
];
SkAst.astnodes.While.prototype._astname = "While";
SkAst.astnodes.While.prototype._fields = [
    "test", function(n) { return n.test; },
    "body", function(n) { return n.body; },
    "orelse", function(n) { return n.orelse; }
];
SkAst.astnodes.If.prototype._astname = "If";
SkAst.astnodes.If.prototype._fields = [
    "test", function(n) { return n.test; },
    "body", function(n) { return n.body; },
    "orelse", function(n) { return n.orelse; }
];
SkAst.astnodes.With.prototype._astname = "With";
SkAst.astnodes.With.prototype._fields = [
    "items", function(n) { return n.items; },
    "body", function(n) { return n.body; }
];
SkAst.astnodes.AsyncWith.prototype._astname = "AsyncWith";
SkAst.astnodes.AsyncWith.prototype._fields = [
    "items", function(n) { return n.items; },
    "body", function(n) { return n.body; }
];
SkAst.astnodes.Raise.prototype._astname = "Raise";
SkAst.astnodes.Raise.prototype._fields = [
    "exc", function(n) { return n.exc; },
    "cause", function(n) { return n.cause; },
    "inst", function(n) { return n.inst; },
    "tback", function(n) { return n.tback; }
];
SkAst.astnodes.Try.prototype._astname = "Try";
SkAst.astnodes.Try.prototype._fields = [
    "body", function(n) { return n.body; },
    "handlers", function(n) { return n.handlers; },
    "orelse", function(n) { return n.orelse; },
    "finalbody", function(n) { return n.finalbody; }
];
SkAst.astnodes.Assert.prototype._astname = "Assert";
SkAst.astnodes.Assert.prototype._fields = [
    "test", function(n) { return n.test; },
    "msg", function(n) { return n.msg; }
];
SkAst.astnodes.Import.prototype._astname = "Import";
SkAst.astnodes.Import.prototype._fields = [
    "names", function(n) { return n.names; }
];
SkAst.astnodes.ImportFrom.prototype._astname = "ImportFrom";
SkAst.astnodes.ImportFrom.prototype._fields = [
    "module", function(n) { return n.module; },
    "names", function(n) { return n.names; },
    "level", function(n) { return n.level; }
];
SkAst.astnodes.Global.prototype._astname = "Global";
SkAst.astnodes.Global.prototype._fields = [
    "names", function(n) { return n.names; }
];
SkAst.astnodes.Nonlocal.prototype._astname = "Nonlocal";
SkAst.astnodes.Nonlocal.prototype._fields = [
    "names", function(n) { return n.names; }
];
SkAst.astnodes.Expr.prototype._astname = "Expr";
SkAst.astnodes.Expr.prototype._fields = [
    "value", function(n) { return n.value; }
];
SkAst.astnodes.Pass.prototype._astname = "Pass";
SkAst.astnodes.Pass.prototype._fields = [
];
SkAst.astnodes.Break.prototype._astname = "Break";
SkAst.astnodes.Break.prototype._fields = [
];
SkAst.astnodes.Continue.prototype._astname = "Continue";
SkAst.astnodes.Continue.prototype._fields = [
];
SkAst.astnodes.Print.prototype._astname = "Print";
SkAst.astnodes.Print.prototype._fields = [
    "dest", function(n) { return n.dest; },
    "values", function(n) { return n.values; },
    "nl", function(n) { return n.nl; }
];
SkAst.astnodes.Debugger.prototype._astname = "Debugger";
SkAst.astnodes.Debugger.prototype._fields = [
];
SkAst.astnodes.BoolOp.prototype._astname = "BoolOp";
SkAst.astnodes.BoolOp.prototype._fields = [
    "op", function(n) { return n.op; },
    "values", function(n) { return n.values; }
];
SkAst.astnodes.BinOp.prototype._astname = "BinOp";
SkAst.astnodes.BinOp.prototype._fields = [
    "left", function(n) { return n.left; },
    "op", function(n) { return n.op; },
    "right", function(n) { return n.right; }
];
SkAst.astnodes.UnaryOp.prototype._astname = "UnaryOp";
SkAst.astnodes.UnaryOp.prototype._fields = [
    "op", function(n) { return n.op; },
    "operand", function(n) { return n.operand; }
];
SkAst.astnodes.Lambda.prototype._astname = "Lambda";
SkAst.astnodes.Lambda.prototype._fields = [
    "args", function(n) { return n.args; },
    "body", function(n) { return n.body; }
];
SkAst.astnodes.IfExp.prototype._astname = "IfExp";
SkAst.astnodes.IfExp.prototype._fields = [
    "test", function(n) { return n.test; },
    "body", function(n) { return n.body; },
    "orelse", function(n) { return n.orelse; }
];
SkAst.astnodes.Dict.prototype._astname = "Dict";
SkAst.astnodes.Dict.prototype._fields = [
    "keys", function(n) { return n.keys; },
    "values", function(n) { return n.values; }
];
SkAst.astnodes.Set.prototype._astname = "Set";
SkAst.astnodes.Set.prototype._fields = [
    "elts", function(n) { return n.elts; }
];
SkAst.astnodes.ListComp.prototype._astname = "ListComp";
SkAst.astnodes.ListComp.prototype._fields = [
    "elt", function(n) { return n.elt; },
    "generators", function(n) { return n.generators; }
];
SkAst.astnodes.SetComp.prototype._astname = "SetComp";
SkAst.astnodes.SetComp.prototype._fields = [
    "elt", function(n) { return n.elt; },
    "generators", function(n) { return n.generators; }
];
SkAst.astnodes.DictComp.prototype._astname = "DictComp";
SkAst.astnodes.DictComp.prototype._fields = [
    "key", function(n) { return n.key; },
    "value", function(n) { return n.value; },
    "generators", function(n) { return n.generators; }
];
SkAst.astnodes.GeneratorExp.prototype._astname = "GeneratorExp";
SkAst.astnodes.GeneratorExp.prototype._fields = [
    "elt", function(n) { return n.elt; },
    "generators", function(n) { return n.generators; }
];
SkAst.astnodes.Await.prototype._astname = "Await";
SkAst.astnodes.Await.prototype._fields = [
    "value", function(n) { return n.value; }
];
SkAst.astnodes.Yield.prototype._astname = "Yield";
SkAst.astnodes.Yield.prototype._fields = [
    "value", function(n) { return n.value; }
];
SkAst.astnodes.YieldFrom.prototype._astname = "YieldFrom";
SkAst.astnodes.YieldFrom.prototype._fields = [
    "value", function(n) { return n.value; }
];
SkAst.astnodes.Compare.prototype._astname = "Compare";
SkAst.astnodes.Compare.prototype._fields = [
    "left", function(n) { return n.left; },
    "ops", function(n) { return n.ops; },
    "comparators", function(n) { return n.comparators; }
];
SkAst.astnodes.Call.prototype._astname = "Call";
SkAst.astnodes.Call.prototype._fields = [
    "func", function(n) { return n.func; },
    "args", function(n) { return n.args; },
    "keywords", function(n) { return n.keywords; }
];
SkAst.astnodes.Num.prototype._astname = "Num";
SkAst.astnodes.Num.prototype._fields = [
    "n", function(n) { return n.n; }
];
SkAst.astnodes.Str.prototype._astname = "Str";
SkAst.astnodes.Str.prototype._fields = [
    "s", function(n) { return n.s; }
];
SkAst.astnodes.FormattedValue.prototype._astname = "FormattedValue";
SkAst.astnodes.FormattedValue.prototype._fields = [
    "value", function(n) { return n.value; },
    "conversion", function(n) { return n.conversion; },
    "format_spec", function(n) { return n.format_spec; }
];
SkAst.astnodes.JoinedStr.prototype._astname = "JoinedStr";
SkAst.astnodes.JoinedStr.prototype._fields = [
    "values", function(n) { return n.values; }
];
SkAst.astnodes.Bytes.prototype._astname = "Bytes";
SkAst.astnodes.Bytes.prototype._fields = [
    "s", function(n) { return n.s; }
];
SkAst.astnodes.NameConstant.prototype._astname = "NameConstant";
SkAst.astnodes.NameConstant.prototype._fields = [
    "value", function(n) { return n.value; }
];
SkAst.astnodes.Ellipsis.prototype._astname = "Ellipsis";
SkAst.astnodes.Ellipsis.prototype._fields = [
];
SkAst.astnodes.Constant.prototype._astname = "Constant";
SkAst.astnodes.Constant.prototype._fields = [
    "value", function(n) { return n.value; }
];
SkAst.astnodes.Attribute.prototype._astname = "Attribute";
SkAst.astnodes.Attribute.prototype._fields = [
    "value", function(n) { return n.value; },
    "attr", function(n) { return n.attr; },
    "ctx", function(n) { return n.ctx; }
];
SkAst.astnodes.Subscript.prototype._astname = "Subscript";
SkAst.astnodes.Subscript.prototype._fields = [
    "value", function(n) { return n.value; },
    "slice", function(n) { return n.slice; },
    "ctx", function(n) { return n.ctx; }
];
SkAst.astnodes.Starred.prototype._astname = "Starred";
SkAst.astnodes.Starred.prototype._fields = [
    "value", function(n) { return n.value; },
    "ctx", function(n) { return n.ctx; }
];
SkAst.astnodes.Name.prototype._astname = "Name";
SkAst.astnodes.Name.prototype._fields = [
    "id", function(n) { return n.id; },
    "ctx", function(n) { return n.ctx; }
];
SkAst.astnodes.List.prototype._astname = "List";
SkAst.astnodes.List.prototype._fields = [
    "elts", function(n) { return n.elts; },
    "ctx", function(n) { return n.ctx; }
];
SkAst.astnodes.Tuple.prototype._astname = "Tuple";
SkAst.astnodes.Tuple.prototype._fields = [
    "elts", function(n) { return n.elts; },
    "ctx", function(n) { return n.ctx; }
];
SkAst.astnodes.Load.prototype._astname = "Load";
SkAst.astnodes.Load.prototype._isenum = true;
SkAst.astnodes.Store.prototype._astname = "Store";
SkAst.astnodes.Store.prototype._isenum = true;
SkAst.astnodes.Del.prototype._astname = "Del";
SkAst.astnodes.Del.prototype._isenum = true;
SkAst.astnodes.AugLoad.prototype._astname = "AugLoad";
SkAst.astnodes.AugLoad.prototype._isenum = true;
SkAst.astnodes.AugStore.prototype._astname = "AugStore";
SkAst.astnodes.AugStore.prototype._isenum = true;
SkAst.astnodes.Param.prototype._astname = "Param";
SkAst.astnodes.Param.prototype._isenum = true;
SkAst.astnodes.Slice.prototype._astname = "Slice";
SkAst.astnodes.Slice.prototype._fields = [
    "lower", function(n) { return n.lower; },
    "upper", function(n) { return n.upper; },
    "step", function(n) { return n.step; }
];
SkAst.astnodes.ExtSlice.prototype._astname = "ExtSlice";
SkAst.astnodes.ExtSlice.prototype._fields = [
    "dims", function(n) { return n.dims; }
];
SkAst.astnodes.Index.prototype._astname = "Index";
SkAst.astnodes.Index.prototype._fields = [
    "value", function(n) { return n.value; }
];
SkAst.astnodes.And.prototype._astname = "And";
SkAst.astnodes.And.prototype._isenum = true;
SkAst.astnodes.Or.prototype._astname = "Or";
SkAst.astnodes.Or.prototype._isenum = true;
SkAst.astnodes.Add.prototype._astname = "Add";
SkAst.astnodes.Add.prototype._isenum = true;
SkAst.astnodes.Sub.prototype._astname = "Sub";
SkAst.astnodes.Sub.prototype._isenum = true;
SkAst.astnodes.Mult.prototype._astname = "Mult";
SkAst.astnodes.Mult.prototype._isenum = true;
SkAst.astnodes.MatMult.prototype._astname = "MatMult";
SkAst.astnodes.MatMult.prototype._isenum = true;
SkAst.astnodes.Div.prototype._astname = "Div";
SkAst.astnodes.Div.prototype._isenum = true;
SkAst.astnodes.Mod.prototype._astname = "Mod";
SkAst.astnodes.Mod.prototype._isenum = true;
SkAst.astnodes.Pow.prototype._astname = "Pow";
SkAst.astnodes.Pow.prototype._isenum = true;
SkAst.astnodes.LShift.prototype._astname = "LShift";
SkAst.astnodes.LShift.prototype._isenum = true;
SkAst.astnodes.RShift.prototype._astname = "RShift";
SkAst.astnodes.RShift.prototype._isenum = true;
SkAst.astnodes.BitOr.prototype._astname = "BitOr";
SkAst.astnodes.BitOr.prototype._isenum = true;
SkAst.astnodes.BitXor.prototype._astname = "BitXor";
SkAst.astnodes.BitXor.prototype._isenum = true;
SkAst.astnodes.BitAnd.prototype._astname = "BitAnd";
SkAst.astnodes.BitAnd.prototype._isenum = true;
SkAst.astnodes.FloorDiv.prototype._astname = "FloorDiv";
SkAst.astnodes.FloorDiv.prototype._isenum = true;
SkAst.astnodes.Invert.prototype._astname = "Invert";
SkAst.astnodes.Invert.prototype._isenum = true;
SkAst.astnodes.Not.prototype._astname = "Not";
SkAst.astnodes.Not.prototype._isenum = true;
SkAst.astnodes.UAdd.prototype._astname = "UAdd";
SkAst.astnodes.UAdd.prototype._isenum = true;
SkAst.astnodes.USub.prototype._astname = "USub";
SkAst.astnodes.USub.prototype._isenum = true;
SkAst.astnodes.Eq.prototype._astname = "Eq";
SkAst.astnodes.Eq.prototype._isenum = true;
SkAst.astnodes.NotEq.prototype._astname = "NotEq";
SkAst.astnodes.NotEq.prototype._isenum = true;
SkAst.astnodes.Lt.prototype._astname = "Lt";
SkAst.astnodes.Lt.prototype._isenum = true;
SkAst.astnodes.LtE.prototype._astname = "LtE";
SkAst.astnodes.LtE.prototype._isenum = true;
SkAst.astnodes.Gt.prototype._astname = "Gt";
SkAst.astnodes.Gt.prototype._isenum = true;
SkAst.astnodes.GtE.prototype._astname = "GtE";
SkAst.astnodes.GtE.prototype._isenum = true;
SkAst.astnodes.Is.prototype._astname = "Is";
SkAst.astnodes.Is.prototype._isenum = true;
SkAst.astnodes.IsNot.prototype._astname = "IsNot";
SkAst.astnodes.IsNot.prototype._isenum = true;
SkAst.astnodes.In.prototype._astname = "In";
SkAst.astnodes.In.prototype._isenum = true;
SkAst.astnodes.NotIn.prototype._astname = "NotIn";
SkAst.astnodes.NotIn.prototype._isenum = true;
SkAst.astnodes.comprehension.prototype._astname = "comprehension";
SkAst.astnodes.comprehension.prototype._fields = [
    "target", function(n) { return n.target; },
    "iter", function(n) { return n.iter; },
    "ifs", function(n) { return n.ifs; },
    "is_async", function(n) { return n.is_async; }
];
SkAst.astnodes.ExceptHandler.prototype._astname = "ExceptHandler";
SkAst.astnodes.ExceptHandler.prototype._fields = [
    "type", function(n) { return n.type; },
    "name", function(n) { return n.name; },
    "body", function(n) { return n.body; }
];
SkAst.astnodes.arguments_.prototype._astname = "arguments";
SkAst.astnodes.arguments_.prototype._fields = [
    "args", function(n) { return n.args; },
    "vararg", function(n) { return n.vararg; },
    "kwonlyargs", function(n) { return n.kwonlyargs; },
    "kw_defaults", function(n) { return n.kw_defaults; },
    "kwarg", function(n) { return n.kwarg; },
    "defaults", function(n) { return n.defaults; }
];
SkAst.astnodes.arg.prototype._astname = "arg";
SkAst.astnodes.arg.prototype._fields = [
    "arg", function(n) { return n.arg; },
    "annotation", function(n) { return n.annotation; }
];
SkAst.astnodes.keyword.prototype._astname = "keyword";
SkAst.astnodes.keyword.prototype._fields = [
    "arg", function(n) { return n.arg; },
    "value", function(n) { return n.value; }
];
SkAst.astnodes.alias.prototype._astname = "alias";
SkAst.astnodes.alias.prototype._fields = [
    "name", function(n) { return n.name; },
    "asname", function(n) { return n.asname; }
];
SkAst.astnodes.withitem.prototype._astname = "withitem";
SkAst.astnodes.withitem.prototype._fields = [
    "context_expr", function(n) { return n.context_expr; },
    "optional_vars", function(n) { return n.optional_vars; }
];

SkAst.exportSymbol("Sk.astnodes", SkAst.astnodes);
